ANY_NEW_IVF_PRODUCT = (
    "any newly introduced, launched, released, or launch-approved product relevant to IVF or ART"
)


INITIAL_SOURCES: list[dict[str, object]] = [
    {
        "name": "CooperSurgical",
        "slug": "cooper-surgical",
        "domain": "coopersurgical.com",
        "website_url": "https://www.coopersurgical.com/",
        "news_url": "https://www.coopersurgical.com/newsroom/",
        "article_url_patterns": ["/press-release/"],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
    {
        "name": "Vitrolife",
        "slug": "vitrolife",
        "domain": "vitrolife.com",
        "website_url": "https://www.vitrolife.com/",
        "news_url": "https://blog.vitrolife.com/togetheralltheway/",
        "article_url_patterns": ["/our-products/"],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
    {
        "name": "Kitazato",
        "slug": "kitazato",
        "domain": "kitazato.co.jp",
        "website_url": "https://www.kitazato.co.jp/en/",
        "news_url": "https://www.kitazato.co.jp/en/ir/ir-all/",
        "article_url_patterns": ["/en/ir/", "/en/images/sites/"],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
    {
        "name": "Esco Medical",
        "slug": "esco-medical",
        "domain": "esco-medical.com",
        "website_url": "https://www.esco-medical.com/",
        "news_url": "https://www.esco-medical.com/home",
        "article_url_patterns": ["/news/"],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
    {
        "name": "Hamilton Thorne",
        "slug": "hamilton-thorne",
        "domain": "hamiltonthorne.com",
        "website_url": "https://www.hamiltonthorne.com/",
        "news_url": "https://www.hamiltonthorne.com/",
        "article_url_patterns": ["/news/", "/press-release/", "/press-releases/"],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
    {
        "name": "Memphasys",
        "slug": "memphasys",
        "domain": "memphasys.com",
        "website_url": "https://www.memphasys.com/",
        "news_url": "https://www.memphasys.com/investor-relations/asx-announcements/",
        "article_url_patterns": ["/wp-content/uploads/"],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
    {
        "name": "Minitube Human ART",
        "slug": "minitube-human-art",
        "domain": "minitube-humanart.com",
        "website_url": "https://www.minitube-humanart.com/",
        "news_url": "https://www.minitube-humanart.com/en/news/",
        "article_url_patterns": ["/en/news/"],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
    {
        "name": "LensHooke",
        "slug": "lenshooke",
        "domain": "lenshooke.com",
        "website_url": "https://lenshooke.com/",
        "news_url": "https://lenshooke.com/news.php",
        "article_url_patterns": ["news.php?id="],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
    {
        "name": "Genea Biomedx",
        "slug": "genea-biomedx",
        "domain": "geneabiomedx.com",
        "website_url": "https://www.geneabiomedx.com/",
        "news_url": "https://www.geneabiomedx.com/blog/",
        "article_url_patterns": ["/geneabiomedx/"],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
    {
        "name": "Sparmed",
        "slug": "sparmed",
        "domain": "sparmed.dk",
        "website_url": "https://www.sparmed.dk/en/",
        "news_url": "https://www.sparmed.dk/en/news/",
        "article_url_patterns": ["/en/news/"],
        "scan_query": ANY_NEW_IVF_PRODUCT,
        "source_type": "MANUFACTURER",
        "enabled": True,
    },
]
